### Exercise 12: Dropout layer

### 12.1) Add a new layer named Dropout to the layers module

In [1]:
import numpy as np

class Dropout(Layer):
    def __init__(self, probability):
        if not 0 <= probability < 1:
            raise ValueError("Error")
        self.probability = probability
        self.mask = None
        self.input = None
        self.output = None

    def forward_propagation(self, input, training=True):
        self.input = input
        if training:
            scaling_factor = 1 / (1 - self.probability)
            self.mask = np.random.binomial(1, 1 - self.probability, size=input.shape)
            self.output = input * self.mask * scaling_factor
        else:
            self.output = input
        return self.output

    def backward_propagation(self, output_error):
        if self.mask is None:
            raise ValueError("Error")
        return output_error * self.mask

    def output_shape(self):
        return self.input.shape

    def parameters(self):
        return 0



NameError: name 'Layer' is not defined

### 12.2) Test the layer with a random input

In [4]:
if __name__ == "__main__":
    np.random.seed(42)  

    dropout_layer = Dropout(probability=0.5)
    test_input = np.array([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])

    # training mode
    print("--- Forward Propagation (Training Mode) ---")
    output_train = dropout_layer.forward_propagation(test_input, training=True)
    print("Input:")
    print(test_input)
    print("Mask:")
    print(dropout_layer.mask)
    print("Output:")
    print(output_train)

    # inference mode
    print("\n--- Forward Propagation (Inference Mode) ---")
    output_inference = dropout_layer.forward_propagation(test_input, training=False)
    print("Input:")
    print(test_input)
    print("Output:")
    print(output_inference)

    # Backward propagation
    print("\n--- Backward Propagation ---")
    output_error = np.array([[0.1, 0.2, 0.3], [0.4, 0.5, 0.6]])
    input_error = dropout_layer.backward_propagation(output_error)
    print("Output Error:")
    print(output_error)
    print("Input Error:")
    print(input_error)


--- Forward Propagation (Training Mode) ---
Input:
[[1. 2. 3.]
 [4. 5. 6.]]
Mask:
[[0 1 1]
 [1 0 0]]
Output:
[[0. 4. 6.]
 [8. 0. 0.]]

--- Forward Propagation (Inference Mode) ---
Input:
[[1. 2. 3.]
 [4. 5. 6.]]
Output:
[[1. 2. 3.]
 [4. 5. 6.]]

--- Backward Propagation ---
Output Error:
[[0.1 0.2 0.3]
 [0.4 0.5 0.6]]
Input Error:
[[0.  0.2 0.3]
 [0.4 0.  0. ]]
